export const OFFICIAL_SOURCES = [
  {
    title: "IELTS Speaking test format",
    publisher: "IELTS",
    url: "https://ielts.org/organisations/ielts-for-organisations/test-types/ielts-academic-test/academic-test-format-in-detail",
    use: "Three-part structure, timing, preparation and long-turn rules",
  },
  {
    title: "IELTS Speaking band descriptors",
    publisher: "IELTS / Cambridge English",
    url: "https://assets.cambridgeenglish.org/webinars/ielts-speaking-band-descriptors.pdf",
    use: "Public descriptors for the four equally weighted criteria",
  },
  {
    title: "IELTS Speaking sample tasks",
    publisher: "IELTS",
    url: "https://ielts.org/cdn/Sample-tests/ielts-speaking-sample-tasks-2023.pdf",
    use: "Task style and examiner interaction pattern",
  },
];

export const PART_ONE_TOPICS = [
  {
    id: "p1-home",
    title: "Home & neighbourhood",
    level: "foundation",
    questions: [
      "What kind of place do you live in?",
      "What do you like most about your neighbourhood?",
      "Is there anything you would like to change about your home?",
      "Do you think you will live in the same area in the future? Why?",
    ],
  },
  {
    id: "p1-study",
    title: "Work or study",
    level: "foundation",
    questions: [
      "Do you work or are you a student?",
      "What do you enjoy most about your work or studies?",
      "What was difficult when you first started?",
      "Would you like to do something different in the future?",
    ],
  },
  {
    id: "p1-mornings",
    title: "Mornings",
    level: "foundation",
    questions: [
      "What is the first thing you usually do in the morning?",
      "Do you prefer busy or relaxed mornings?",
      "Has your morning routine changed in recent years?",
      "What would make your mornings better?",
    ],
  },
  {
    id: "p1-friends",
    title: "Friends",
    level: "foundation",
    questions: [
      "How often do you spend time with friends?",
      "What do you usually do together?",
      "Do you prefer having a few close friends or many friends?",
      "Is it easy for you to make new friends?",
    ],
  },
  {
    id: "p1-food",
    title: "Food & cooking",
    level: "foundation",
    questions: [
      "What kind of food do you enjoy eating?",
      "How often do you cook for yourself?",
      "Did you help with cooking when you were a child?",
      "Is there a dish you would like to learn to make?",
    ],
  },
  {
    id: "p1-weekends",
    title: "Weekends",
    level: "foundation",
    questions: [
      "What do you normally do at weekends?",
      "Are your weekends different from your weekdays?",
      "What did you do last weekend?",
      "How would you spend an ideal weekend?",
    ],
  },
  {
    id: "p1-reading",
    title: "Reading",
    level: "developing",
    questions: [
      "Do you read much in your daily life?",
      "What kind of things do you prefer to read?",
      "Did anyone encourage you to read when you were younger?",
      "Do you think your reading habits will change in the future?",
    ],
  },
  {
    id: "p1-transport",
    title: "Transport",
    level: "developing",
    questions: [
      "How do you usually travel around your town or city?",
      "What do you like or dislike about that form of transport?",
      "Is public transport popular where you live?",
      "Would you like to use a different form of transport in the future?",
    ],
  },
  {
    id: "p1-music",
    title: "Music",
    level: "developing",
    questions: [
      "When do you usually listen to music?",
      "What kind of music do you enjoy most?",
      "Has your taste in music changed over time?",
      "Do you think music is important for children?",
    ],
  },
  {
    id: "p1-photos",
    title: "Photos",
    level: "developing",
    questions: [
      "How often do you take photographs?",
      "What do you usually photograph?",
      "Do you prefer keeping photos digitally or printing them?",
      "Why do people like looking at old photographs?",
    ],
  },
  {
    id: "p1-weather",
    title: "Weather",
    level: "developing",
    questions: [
      "What is the weather usually like where you live?",
      "What kind of weather do you enjoy most?",
      "Does the weather affect what you do?",
      "Would you like to live somewhere with a different climate?",
    ],
  },
  {
    id: "p1-technology",
    title: "Everyday technology",
    level: "developing",
    questions: [
      "Which piece of technology do you use most often?",
      "How does it make your daily life easier?",
      "Is there any technology you find difficult to use?",
      "Do you try to spend time away from screens?",
    ],
  },
  {
    id: "p1-parks",
    title: "Parks & green spaces",
    level: "advanced",
    questions: [
      "Are there many green spaces near your home?",
      "When did you last visit a park?",
      "What do people in your area do in parks?",
      "How could local green spaces be improved?",
    ],
  },
  {
    id: "p1-gifts",
    title: "Gifts",
    level: "advanced",
    questions: [
      "Do you enjoy choosing gifts for other people?",
      "What was the last gift you received?",
      "Do you prefer practical or memorable gifts?",
      "Have gift-giving traditions changed in your country?",
    ],
  },
  {
    id: "p1-learning",
    title: "Learning skills",
    level: "advanced",
    questions: [
      "What new skill have you learned recently?",
      "Do you learn better alone or with other people?",
      "What helps you continue when learning is difficult?",
      "Which skill would you most like to learn next?",
    ],
  },
  {
    id: "p1-noise",
    title: "Noise & quiet",
    level: "advanced",
    questions: [
      "Is your neighbourhood usually quiet or noisy?",
      "What kinds of sound do you find pleasant?",
      "When do you need complete silence?",
      "Do you think modern life is becoming noisier?",
    ],
  },
];

export const CUE_CARDS = [
  {
    id: "p2-helpful-person",
    title: "A person who gave you useful help",
    prompt: "Describe a person who gave you useful help.",
    bullets: ["who the person was", "when and why you needed help", "what the person did", "how the help affected you"],
    followUp: "Would you help this person in the same way?",
    part3Theme: "help and community",
    part3: [
      "Why are some people more willing to help strangers than others?",
      "Should schools require students to take part in community service?",
      "How has technology changed the way people ask for help?",
      "Can too much help prevent a person from becoming independent?",
    ],
    level: "foundation",
  },
  {
    id: "p2-pleasant-journey",
    title: "A journey you enjoyed",
    prompt: "Describe a journey that you enjoyed.",
    bullets: ["where you went", "who you travelled with", "what happened during the journey", "why you remember it positively"],
    followUp: "Would you like to make that journey again?",
    part3Theme: "travel and transport",
    part3: [
      "Why do some journeys remain in people's memories for a long time?",
      "How can cities encourage people to use public transport?",
      "Will virtual experiences ever replace physical travel?",
      "Who should pay for improvements to transport infrastructure?",
    ],
    level: "foundation",
  },
  {
    id: "p2-useful-object",
    title: "A useful object in your home",
    prompt: "Describe an object in your home that you find especially useful.",
    bullets: ["what it is", "how long you have had it", "how you use it", "why it is important to you"],
    followUp: "Do other people in your home use it too?",
    part3Theme: "objects and consumption",
    part3: [
      "Why do people become attached to ordinary objects?",
      "Are modern household products designed to last?",
      "How does advertising influence what people consider necessary?",
      "Should manufacturers be responsible for repairing old products?",
    ],
    level: "foundation",
  },
  {
    id: "p2-happy-event",
    title: "An event that made you happy",
    prompt: "Describe an event that made you feel happy.",
    bullets: ["what the event was", "where and when it happened", "who was there", "why it made you happy"],
    followUp: "Did you tell anyone else about the event?",
    part3Theme: "happiness and society",
    part3: [
      "Do people of different ages find happiness in different things?",
      "Why can shared experiences feel more rewarding than possessions?",
      "Should governments measure the happiness of citizens?",
      "Has social media changed how people show that they are happy?",
    ],
    level: "foundation",
  },
  {
    id: "p2-skill",
    title: "A skill you learned",
    prompt: "Describe a practical skill that you learned.",
    bullets: ["what the skill is", "why you decided to learn it", "how you learned it", "how useful it has been"],
    followUp: "Is there more you would like to learn about it?",
    part3Theme: "skills and education",
    part3: [
      "Which practical skills should all young people learn?",
      "Is learning through experience more effective than classroom learning?",
      "How should employers support workers who need new skills?",
      "Will technology make some human skills unnecessary?",
    ],
    level: "foundation",
  },
  {
    id: "p2-crowded-place",
    title: "A crowded place",
    prompt: "Describe a crowded place you have visited.",
    bullets: ["where the place was", "when you went there", "what people were doing", "how you felt about being there"],
    followUp: "Would you choose to visit it again?",
    part3Theme: "crowds and urban life",
    part3: [
      "Why are some people comfortable in crowds while others are not?",
      "What problems does overcrowding create in cities?",
      "Can good urban design make crowded places more pleasant?",
      "Why do major public events continue to attract large audiences?",
    ],
    level: "developing",
  },
  {
    id: "p2-conversation",
    title: "An interesting conversation",
    prompt: "Describe an interesting conversation you had with someone.",
    bullets: ["who you spoke with", "where the conversation happened", "what you discussed", "why it interested you"],
    followUp: "Did the conversation change your opinion?",
    part3Theme: "communication",
    part3: [
      "What makes someone a good conversationalist?",
      "Are face-to-face conversations becoming less common?",
      "Why is respectful disagreement important in society?",
      "How can people communicate well across cultural differences?",
    ],
    level: "developing",
  },
  {
    id: "p2-local-business",
    title: "A local business you value",
    prompt: "Describe a local business that you think is valuable to your area.",
    bullets: ["what the business is", "where it is", "what it provides", "why it matters to local people"],
    followUp: "How often do you use this business?",
    part3Theme: "business and communities",
    part3: [
      "Why do some customers prefer small businesses to large companies?",
      "What difficulties do new businesses commonly face?",
      "Should governments protect local shops from large online retailers?",
      "How might shopping habits change over the next twenty years?",
    ],
    level: "developing",
  },
  {
    id: "p2-film",
    title: "A film that stayed with you",
    prompt: "Describe a film that you continued thinking about after watching it.",
    bullets: ["what the film was", "when you watched it", "what it was about", "why it stayed in your mind"],
    followUp: "Would you recommend this film to everyone?",
    part3Theme: "film and storytelling",
    part3: [
      "Why do stories have such a strong influence on people?",
      "Should films mainly entertain or also educate audiences?",
      "How has streaming changed the kinds of films that are produced?",
      "Can films improve understanding between cultures?",
    ],
    level: "developing",
  },
  {
    id: "p2-outdoor-place",
    title: "An outdoor place",
    prompt: "Describe an outdoor place where you like spending time.",
    bullets: ["where it is", "what it looks like", "what you do there", "why you enjoy being there"],
    followUp: "Is this place popular with other people?",
    part3Theme: "public and natural spaces",
    part3: [
      "Why is access to outdoor space important in large cities?",
      "Who should be responsible for protecting natural places?",
      "Can tourism and environmental protection exist together?",
      "How might climate change affect the way people use outdoor spaces?",
    ],
    level: "developing",
  },
  {
    id: "p2-difficult-decision",
    title: "A difficult decision",
    prompt: "Describe a difficult decision that you made.",
    bullets: ["what you had to decide", "why the decision was difficult", "who or what helped you", "how you felt about the result"],
    followUp: "Would you make the same decision now?",
    part3Theme: "decision-making",
    part3: [
      "Why do some people make important decisions quickly?",
      "How much should parents influence the decisions of young adults?",
      "Are group decisions usually better than individual decisions?",
      "What role should data play in government decision-making?",
    ],
    level: "developing",
  },
  {
    id: "p2-improvement",
    title: "A change that improved your area",
    prompt: "Describe a change that improved the area where you live.",
    bullets: ["what changed", "when it happened", "who benefited", "why you consider it an improvement"],
    followUp: "Is any further improvement needed?",
    part3Theme: "communities and development",
    part3: [
      "How should authorities decide which local improvements to fund?",
      "Why do residents sometimes oppose changes to their neighbourhoods?",
      "Should historic areas be preserved even when cities need more housing?",
      "How can ordinary citizens influence local planning decisions?",
    ],
    level: "advanced",
  },
  {
    id: "p2-rule",
    title: "A rule you consider important",
    prompt: "Describe a rule that you believe is important.",
    bullets: ["what the rule is", "where it applies", "why it is needed", "what might happen without it"],
    followUp: "Is the rule always enforced fairly?",
    part3Theme: "rules and responsibility",
    part3: [
      "Why are some rules widely accepted while others are resisted?",
      "Should the same rules apply to everyone in every situation?",
      "How can authorities encourage compliance without punishment?",
      "When is it reasonable for an old law to be changed?",
    ],
    level: "advanced",
  },
  {
    id: "p2-environmental-action",
    title: "An environmental action",
    prompt: "Describe something you do to reduce your environmental impact.",
    bullets: ["what you do", "when you started doing it", "how easy or difficult it is", "why you think it matters"],
    followUp: "Could you persuade other people to do the same?",
    part3Theme: "environmental responsibility",
    part3: [
      "Can individual choices make a meaningful environmental difference?",
      "Should environmentally harmful products cost more?",
      "How can businesses be made accountable for environmental damage?",
      "Why is long-term environmental planning difficult for governments?",
    ],
    level: "advanced",
  },
  {
    id: "p2-unexpected-news",
    title: "Unexpected good news",
    prompt: "Describe a time when you received unexpected good news.",
    bullets: ["what the news was", "how you received it", "who you told", "how it affected you"],
    followUp: "Do you still think about that news?",
    part3Theme: "news and information",
    part3: [
      "Why are people attracted to unexpected news stories?",
      "Has instant access to news improved people's understanding of events?",
      "What responsibilities do people have before sharing information online?",
      "Should positive news receive more attention from the media?",
    ],
    level: "advanced",
  },
  {
    id: "p2-teacher",
    title: "A teacher who influenced you",
    prompt: "Describe a teacher who had a positive influence on you.",
    bullets: ["who the teacher was", "what they taught", "what made their approach effective", "how they influenced you"],
    followUp: "Have you ever thanked this teacher?",
    part3Theme: "teaching and learning",
    part3: [
      "What personal qualities make someone an effective teacher?",
      "How should the role of teachers change as technology develops?",
      "Should student results be used to judge teacher performance?",
      "What can schools do that online courses cannot?",
    ],
    level: "advanced",
  },
  {
    id: "p2-tradition",
    title: "A tradition worth keeping",
    prompt: "Describe a tradition that you think should continue.",
    bullets: ["what the tradition is", "who takes part", "how it is practised", "why it should be preserved"],
    followUp: "Has this tradition changed during your lifetime?",
    part3Theme: "tradition and change",
    part3: [
      "Why do some traditions survive while others disappear?",
      "Can a tradition remain authentic if it changes over time?",
      "Should public money be used to preserve cultural traditions?",
      "How does migration influence the traditions of a society?",
    ],
    level: "advanced",
  },
  {
    id: "p2-technology-problem",
    title: "A problem solved with technology",
    prompt: "Describe a time when technology helped you solve a problem.",
    bullets: ["what the problem was", "which technology you used", "what you did", "how effective the solution was"],
    followUp: "Could the problem have been solved without technology?",
    part3Theme: "technology and problem-solving",
    part3: [
      "Does technology make people better problem-solvers?",
      "Which problems should never be left entirely to automated systems?",
      "How can societies reduce inequality in access to technology?",
      "Should innovation be slowed down until its risks are understood?",
    ],
    level: "advanced",
  },
];

export const ALL_TOPICS = [
  ...PART_ONE_TOPICS.map((topic) => ({ ...topic, type: "part1" })),
  ...CUE_CARDS.map((topic) => ({ ...topic, type: "part2" })),
];

export const PLAN_DAYS = [
  ["Baseline, not perfection", "Complete a short diagnostic. Speak naturally so the coach can find your real starting point.", "diagnostic", 15],
  ["Build a full answer", "Use answer + reason + specific detail for familiar Part 1 topics.", "part1", 15],
  ["Remove empty fillers", "Replace repeated um/like/you know with a calm silent pause.", "fluency", 15],
  ["Make grammar dependable", "Control present, past and future forms in short personal answers.", "grammar", 18],
  ["Speak clearly, not quickly", "Prioritise thought groups, sentence stress and complete word endings.", "pronunciation", 15],
  ["First long turn", "Plan four anchors in 60 seconds, then speak for 90–120 seconds.", "part2", 20],
  ["Week 1 checkpoint", "Repeat the diagnostic format and compare evidence, not just the score.", "checkpoint", 20],
  ["Connect ideas naturally", "Use referencing and logical links without forcing memorised connectors.", "coherence", 18],
  ["Tell a clear story", "Sequence an event and make past-time relationships precise.", "part2", 20],
  ["Paraphrase flexibly", "Explain an idea a second way when the exact word does not arrive.", "lexical", 18],
  ["Develop reasons", "Move from claim to reason, example and consequence in Part 3.", "part3", 20],
  ["Use complex grammar safely", "Practise conditionals and relative clauses only where meaning needs them.", "grammar", 20],
  ["Sound engaged", "Vary stress and intonation to show contrast, attitude and key information.", "pronunciation", 18],
  ["Week 2 checkpoint", "Complete Parts 1 and 2 under authentic timing.", "checkpoint", 22],
  ["Handle abstract questions", "Compare groups, causes and effects without losing a clear position.", "part3", 22],
  ["Precision over fancy words", "Choose accurate collocations and correct any vague wording naturally.", "lexical", 18],
  ["Extend without repetition", "Add a different dimension: example, contrast, cause or future effect.", "fluency", 20],
  ["Unfamiliar cue cards", "Use what/when/who/why anchors when the topic is not immediately comfortable.", "part2", 22],
  ["Challenge your own view", "Give a position, limitation and balanced conclusion in Part 3.", "part3", 22],
  ["Repair naturally", "Clarify or correct a slip once, then continue without restarting the sentence.", "fluency", 18],
  ["Week 3 full mock", "Complete all three parts with examiner-style transitions and no coaching.", "mock", 18],
  ["Target your weakest criterion", "Use your progress evidence to train the lowest scoring criterion.", "adaptive", 20],
  ["Part 1: concise confidence", "Answer directly, extend naturally and stop before becoming repetitive.", "part1", 18],
  ["Part 2: two-minute control", "Sustain the long turn with clear stages and relevant detail.", "part2", 20],
  ["Part 3: depth and nuance", "Discuss trade-offs, exceptions and longer-term consequences.", "part3", 22],
  ["Pronunciation under pressure", "Maintain clear chunking and pace while developing complex ideas.", "pronunciation", 18],
  ["Full mock: new topics", "Run a fresh 11–14 minute simulation. Review only after it ends.", "mock", 18],
  ["Evidence-led repair", "Re-answer three weak questions using one precise improvement each.", "adaptive", 20],
  ["Final rehearsal", "Use authentic conditions; focus on communication, not a target score.", "mock", 18],
  ["Test-ready review", "Compare Day 1 and Day 30, save your final priorities and recovery plan.", "checkpoint", 20],
].map(([title, description, focus, minutes], index) => ({
  day: index + 1,
  title,
  description,
  focus,
  minutes,
  phase: index < 7 ? "Foundation" : index < 14 ? "Control" : index < 21 ? "Develop" : "Perform",
}));

export const RUBRIC_SUMMARY = {
  fluency: {
    label: "Fluency & coherence",
    short: "Flow, logical development, cohesive use, repetition and self-correction.",
  },
  lexical: {
    label: "Lexical resource",
    short: "Range, precision, flexibility, paraphrase and natural idiomatic use.",
  },
  grammar: {
    label: "Grammar range & accuracy",
    short: "Varied structures used naturally, with the proportion of error-free speech.",
  },
  pronunciation: {
    label: "Pronunciation",
    short: "Intelligibility plus flexible stress, rhythm, intonation and sound control.",
  },
};

export function getPlanDay(startDate, now = new Date()) {
  if (!startDate) return 1;
  const start = new Date(`${startDate}T00:00:00`);
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const elapsed = Math.floor((today - start) / 86400000) + 1;
  return Math.min(30, Math.max(1, elapsed));
}

export function pickRandom(items, count = 1, excludeIds = []) {
  const pool = items.filter((item) => !excludeIds.includes(item.id));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
